name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push user-service
        run: |
          docker build -t kathuriagautam2411/user-service:latest ./user-service
          docker push kathuriagautam2411/user-service:latest

      - name: Build and push product-service
        run: |
          docker build -t kathuriagautam2411/product-service:latest ./product-service
          docker push kathuriagautam2411/product-service:latest

      - name: Build and push frontend
        run: |
          docker build -t kathuriagautam2411/frontend:latest ./frontend
          docker push kathuriagautam2411/frontend:latest

